### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by geoffviola** [ros-arm-gbp/roscpp_core-release#1]
Would it be possible for another release to be issued? I have a project downstream that could use changes from the roscpp_serialization particularly for the ARM release.

**Comment by trainman419** [comment]
This package does not make changes to roscpp_serialization for ARM; it just existed to remove the dependency on SBCL (lisp) back when Ubuntu did not provide builds of SBCL for armhf.

Now that the SBCL packages for ARM are included with Ubuntu 14.04 and newer, this package is obsolete.

**Comment by geoffviola** [comment]
Thanks. I was confused about this repository. I moved my question to https://github.com/ros-gbp/roscpp_core-release/issues/1.
